# Generated by Django 3.2 on 2022-11-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20221006_1336'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
