# Generated by Django 3.2.16 on 2022-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_section_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_student_num',
            field=models.IntegerField(default=1),
        ),
    ]
