# Generated by Django 3.2.20 on 2023-09-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_delete_sectionteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sub_school',
        ),
    ]
