# Generated by Django 3.2.16 on 2022-12-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prop_degree'),
        ('teacher', '0002_auto_20221006_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.degree'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prop_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prop_degree'),
        ),
    ]
