# Generated by Django 3.2.16 on 2022-12-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20221205_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='prop_degree',
        ),
    ]
