# Generated by Django 3.2.16 on 2022-12-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_prop_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='access',
            field=models.CharField(choices=[('A_1', 'Сургууль'), ('A_2', 'Салбар сургууль'), ('A_3', 'Тэнхим'), ('A_4', 'Багш'), ('A_5', 'Туслах багш')], default='A_4', max_length=10),
        ),
    ]
