# Generated by Django 3.2.16 on 2022-12-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='access',
            field=models.CharField(choices=[('A_1', 'Багш'), ('A_2', 'Туслах багш')], default='A_1', max_length=10),
        ),
    ]
