# Generated by Django 3.2.15 on 2022-12-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prop_degree'),
        ('teacher', '0006_alter_teacher_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='prop_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prop_degree'),
        ),
    ]
