# Generated by Django 3.2.15 on 2022-12-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0004_sectionteacher'),
        ('employee', '0005_rename_employee_compartment_employee_compartment'),
        ('subject', '0005_alter_subject_credit'),
        ('teacher', '0006_alter_teacher_access'),
        ('schoolyear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyear.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'permissions': [('approve_plan', 'Can approve plan')],
            },
        ),
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('goal', models.TextField()),
                ('teaching_methods', models.TextField()),
                ('consumables', models.TextField()),
                ('walk', models.CharField(blank=True, max_length=150, null=True)),
                ('running', models.CharField(blank=True, max_length=150, null=True)),
                ('jumping', models.CharField(blank=True, max_length=150, null=True)),
                ('shoot', models.CharField(blank=True, max_length=150, null=True)),
                ('hand', models.CharField(blank=True, max_length=150, null=True)),
                ('body', models.CharField(blank=True, max_length=150, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubPlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('teacher_activity', models.TextField(blank=True)),
                ('student_activity', models.TextField(blank=True)),
                ('sub_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.subplan')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('monday', models.TextField(blank=True, null=True)),
                ('tuesday', models.TextField(blank=True, null=True)),
                ('wednesday', models.TextField(blank=True, null=True)),
                ('thursday', models.TextField(blank=True, null=True)),
                ('friday', models.TextField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('all_day', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
        ),
    ]
