# Generated by Django 3.2.15 on 2022-12-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='game',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
