# Generated by Django 3.2.20 on 2023-09-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20230815_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='subject',
        ),
        migrations.AddField(
            model_name='subplan',
            name='subjectName',
            field=models.CharField(choices=[('LANGUAGE', 'Хэл яриа'), ('MOVEMENT', 'Хөдөлгөөн, эрүүл мэнд'), ('NATURE', 'Байгаль, нийгмийн ухаан'), ('MATH', 'Математикийн энгийн төсөөлөл'), ('ART', 'Дүрслэх урлаг'), ('MUSIC', 'Дуу хөгжим')], default='LANGUAGE', max_length=50),
        ),
    ]
