# Generated by Django 3.2.20 on 2023-09-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20230921_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subplan',
            old_name='subjectName',
            new_name='subject_name',
        ),
    ]
