# Generated by Django 3.2.15 on 2022-12-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_alter_subject_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='part',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_eng',
        ),
    ]
