# Generated by Django 3.2.15 on 2022-12-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20221228_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_mgl',
        ),
    ]
