# Generated by Django 3.2.15 on 2022-12-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_remove_subject_subject_mgl'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
