# Generated by Django 3.2.20 on 2023-09-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
