# Generated by Django 3.2.16 on 2023-02-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolyear', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='season',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='semester_code',
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(),
        ),
    ]
