# Generated by Django 3.2.18 on 2023-08-10 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_auto_20221125_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(choices=[('Good', 'Сайн'), ('NORMAL', 'Хэвийн'), ('BAD', 'Муу')], max_length=20)),
                ('physical_condition', models.CharField(max_length=200)),
                ('sleep_morning', models.CharField(max_length=200)),
                ('sleep_afternoon', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('body_temperature', models.CharField(max_length=200)),
                ('poo_morning', models.CharField(choices=[('HARD', 'Хатуу'), ('NORMAL', 'Хэвийн'), ('LIQUID', 'Шингэн'), ('DIARRHEA', 'Гүйлгэсэн')], max_length=20)),
                ('poo_morning_count', models.IntegerField(default=0)),
                ('poo_afternoon', models.CharField(choices=[('HARD', 'Хатуу'), ('NORMAL', 'Хэвийн'), ('LIQUID', 'Шингэн'), ('DIARRHEA', 'Гүйлгэсэн')], max_length=20)),
                ('poo_afternoon_count', models.IntegerField(default=0)),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
