# Generated by Django 3.2.18 on 2023-08-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
