# Generated by Django 3.2.18 on 2023-08-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0002_auto_20230811_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='behavior',
            field=models.CharField(choices=[('GOOD', 'Сайн'), ('NORMAL', 'Хэвийн'), ('BAD', 'Муу')], max_length=20),
        ),
    ]
