# Generated by Django 3.2.20 on 2023-10-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0003_alter_contactbook_behavior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactbook',
            old_name='description',
            new_name='word_to_say',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='body_temperature',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='food',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='poo_afternoon',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='poo_afternoon_count',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='poo_morning',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='poo_morning_count',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='sleep_afternoon',
        ),
        migrations.RemoveField(
            model_name='contactbook',
            name='sleep_morning',
        ),
        migrations.AddField(
            model_name='contactbook',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactbook',
            name='defecate_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactbook',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='static/uploads/default/contact_book/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='contactbook',
            name='is_morning_food_eat',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='contactbook',
            name='is_sleep',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactbook',
            name='physical_condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
