# Generated by Django 3.2.20 on 2023-10-23 06:49

import apps.handover.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_auto_20221125_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', apps.handover.models.UniqueCodeField(unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
