# Generated by Django 3.2.20 on 2023-10-23 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='create_userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handover',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
