# Generated by Django 3.2.20 on 2023-10-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0002_auto_20231023_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='is_successed',
            field=models.BooleanField(default=False),
        ),
    ]
