# Generated by Django 3.2.15 on 2022-12-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address_live',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
    ]
