# Generated by Django 3.2 on 2022-11-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='classes_mgl',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='end_course',
        ),
    ]
