# Generated by Django 3.2.16 on 2022-12-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_classes_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='max_student_num',
        ),
    ]
