# Generated by Django 3.2.16 on 2022-12-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classes_max_student_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='classes_numeric',
        ),
    ]
