# Generated by Django 3.2.23 on 2024-11-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_remove_subject_teacher'),
        ('online_lesson', '0005_auto_20230413_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
