# Generated by Django 3.2 on 2022-11-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='degree',
        ),
    ]
