# Generated by Django 3.2.20 on 2023-10-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0003_remove_program_program_numeric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flex_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='Flex_time_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('MORNING', 'Өглөөний үйл ажиллагаа'), ('AFTERNOON', 'Өдрийн үйл ажиллагаа'), ('EVENING', 'Оройн үйл ажиллагаа')], default='MORNING', max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('content', models.TextField()),
                ('flex_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flextime.flex_time')),
            ],
        ),
    ]
