# Generated by Django 3.2.20 on 2023-10-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flextime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flex_time_sub',
            name='period',
        ),
    ]
