# Generated by Django 3.2 on 2022-11-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_address_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='family_name_mgl',
        ),
        migrations.RemoveField(
            model_name='student',
            name='join_before',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name_mgl',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone2',
        ),
    ]
