# Generated by Django 3.2.23 on 2025-05-28 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20221125_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='student',
            name='expire_date',
            field=models.DateTimeField(default=datetime.date(2025, 5, 27)),
        ),
    ]
