# Generated by Django 3.2.23 on 2025-05-29 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_program_program_numeric'),
        ('section', '0006_remove_section_sub_school'),
        ('classes', '0006_remove_classes_sub_school'),
        ('school', '0002_school_location'),
        ('student', '0005_auto_20250528_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='create_userID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registerNo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expire_date',
            field=models.DateTimeField(default=datetime.date(2025, 5, 28)),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
    ]
